# Generated by Django 5.2.17 on 2026-09-13 01:46

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('code', models.CharField(default=accounts.models.generate_otp_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_otp_expiry)),
                ('pending_signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PendingSignup',
                'ordering': ['-created_at', '-pending_signup_id'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('code', models.CharField(default=accounts.models.generate_otp_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_otp_expiry)),
                ('one_time_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password reset')], max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OneTimeCode',
                'ordering': ['-created_at', '-one_time_code_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'purpose'), name='one_live_code_per_user_and_purpose')],
            },
        ),
    ]
