# Generated by Django 5.2.17 on 2026-09-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingsignup_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='dietary_preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
