"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

import environ

# True under `manage.py test` (sys.argv[1] == 'test') or pytest (which
# imports itself into sys.modules before Django's settings are ever read).
# Used below to turn off DRF throttling for the test run only - the rates
# are real limits meant to bound an hour or a day of live traffic, and every
# throttle class shares one cache bucket per client with no reset between
# test methods, so the full suite - hundreds of requests from the test
# client's one fixed IP - would start tripping them by sheer accumulated
# count, not because anything under test is actually being abusive.
# accounts/tests.py exercises the real throttle behaviour anyway, via
# @override_settings(REST_FRAMEWORK=...) scoped to just those tests - DRF's
# APISettings listens for setting_changed, so that override is honoured even
# though TESTING itself is fixed at import time and cannot be un-set that way.
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test' or 'pytest' in sys.modules

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read configuration from environment variables, falling back to the defaults
# below so a fresh clone runs without a .env file. No .env of any kind is
# committed - README.md lists the keys and what each one does.
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CORS_ALLOWED_ORIGINS=(list, ['http://localhost:3000', 'http://127.0.0.1:3000']),
)
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'SECRET_KEY',
    default='django-insecure-=ql$!y7ntt6q_i*eef@_9101061=*jk8+)6s3or_w@%*nlhenl',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Production hardening. Everything here is scoped to DEBUG=False so local
# development is unaffected - none of it works over plain http, and turning
# it on locally just makes the dev server unreachable.
if not DEBUG:
    # Render terminates TLS at its proxy and forwards over http, so Django
    # only learns the original request was https from this header. Without
    # it, SECURE_SSL_REDIRECT sees http and redirects forever.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Start at one hour. Raise it once the deployment is known good - HSTS is
    # hard to walk back, since browsers cache the instruction for its full
    # duration and will refuse http for that long.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    # Stores issued refresh tokens so logout and rotation can revoke them.
    # Adds two tables; they are framework infrastructure, not part of the ERD.
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    # Uploads only. Image.url is a plain URLField, so Cloudinary is never
    # wired in as a Django storage backend - see CLOUDINARY_STORAGE below.
    'cloudinary',

    'accounts',
    'dashboard',
    'meal_plans',
    'recipes',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CorsMiddleware must sit above CommonMiddleware so CORS headers are
    # attached even to responses CommonMiddleware short-circuits.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Defaults to the local SQLite file so a fresh clone runs with no setup.
# Set DATABASE_URL to point at the real MySQL database once it is provisioned,
# e.g. mysql://user:password@127.0.0.1:3306/flavorshare
if env('DATABASE_URL', default=None):
    DATABASES = {'default': env.db('DATABASE_URL')}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded media (local dev; Cloudinary takes over in production)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Cloudinary
# https://cloudinary.com/documentation/django_integration
#
# Recipe photos are uploaded through POST /api/recipes/images/upload/, which
# hands the file to Cloudinary server-side and returns the hosted URL. Only
# that URL is stored, in Image.url - a plain URLField - so Cloudinary is never
# registered as a Django storage backend and STORAGES stays untouched. Keeping
# the API secret on this side is the point: the frontend never sees it.
#
# Blank by default so a fresh clone still starts. The upload endpoint checks
# for CLOUD_NAME and answers 503 with a readable message rather than failing
# somewhere inside the SDK. README.md lists the keys.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': env('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
}

# Largest file the upload endpoint will accept, in bytes. Checked before the
# file is sent anywhere, so an oversized upload costs nothing.
MAX_IMAGE_UPLOAD_BYTES = 10 * 1024 * 1024


# Brevo
# https://developers.brevo.com/reference/sendtransacemail
#
# Outbound email for signup verification codes and password resets, sent from
# accounts/emails.py. Only the API key lives on this side; the frontend never
# sees it, and nothing about a code is ever returned in an API response.
#
# Blank by default so a fresh clone still starts and the test suite still runs -
# the suite mocks the SDK throughout and never needs a real key.
# accounts/emails.py raises EmailNotConfigured when either setting is missing,
# which the views turn into a readable 503 rather than an error from inside the
# SDK. README.md lists both.
BREVO_API_KEY = env('BREVO_API_KEY', default='')

# The From address, as either "you@example.com" or "Name <you@example.com>" -
# accounts/emails.py splits it with email.utils.parseaddr, so both work.
#
# No default, unlike the Resend setup this replaced. Resend shipped a sandbox
# sender that worked out of the box but could only deliver to the account
# owner's own inbox; Brevo has no equivalent, and without a verified domain it
# requires the From address to be a real mailbox you control. There is no value
# that would work for an arbitrary clone, so a missing one is treated as
# "not configured" rather than papered over with a guess.
BREVO_FROM_EMAIL = env('BREVO_FROM_EMAIL', default='')

# TheMealDB
# https://www.themealdb.com/api.php
#
# Used only by `manage.py import_themealdb` (recipes/management/commands) to
# seed the catalogue. '1' is TheMealDB's own published test key - free, no
# signup, rate-limited - so a fresh clone can run the import with no setup.
# Swap in a registered key here if the free one starts throttling.
THEMEALDB_API_KEY = env('THEMEALDB_API_KEY', default='1')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Locked down by default: each view opts out with permission_classes.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # A multiple of both 2 and 3, not a round number for its own sake: the
    # Explore page's recipe grid is grid-cols-2 on tablet and grid-cols-3 on
    # desktop (RecipeResults.tsx), and a page size that is not a multiple of
    # the column count leaves the last row visibly short - a page of 20 in
    # 3 columns ends 6 full rows then a row of 2, with an empty third column
    # where a card would go. 18 divides evenly into both layouts, so only
    # the very last page of a recipe list can ever fall short now, not
    # every full page along the way.
    'PAGE_SIZE': 18,

    # Rate limiting. 'anon'/'user' are the project-wide baseline every view
    # gets unless it declares its own throttle_classes; 'auth_email' and
    # 'otp_verify' belong to the five accounts views that do
    # (accounts/views.py carries the reasoning for each). Generous enough
    # that normal use never notices: a signed-in session polling a few
    # endpoints in parallel is nowhere near 1000/hour, and a real person
    # resending a missed code twice is nowhere near 5/hour - these numbers
    # are sized against scripted abuse, not against anyone actually using
    # the app.
    #
    # Every rate is None during the test run instead - see TESTING's own
    # comment above for why - rather than just emptying DEFAULT_THROTTLE_CLASSES.
    # A view with its own throttle_classes (the accounts five) never
    # consults that default at all, so disabling it there would do nothing
    # for exactly the views this project actually throttles; a None rate
    # makes SimpleRateThrottle.allow_request() return True unconditionally
    # for every throttle class, reached through either list.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': None if TESTING else '100/hour',
        'user': None if TESTING else '1000/hour',
        # Register / resend-otp / password-reset-request: caps how often
        # this server will ask Brevo to send mail from one IP, so scripted
        # signups cannot spend the 300-a-day free quota real users need.
        'auth_email': None if TESTING else '5/hour',
        # Verify-email / password-reset-confirm: a code is six digits, one
        # in a million - safe from guessing only if guessing is this slow.
        'otp_verify': None if TESTING else '10/hour',
    },
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    # Our User model's primary key is `user_id`, not Django's default `id`.
    # Without this SimpleJWT reads user.id when issuing a token and raises
    # AttributeError. USER_ID_CLAIM is already the default; stated here so
    # the pair stays visibly linked.
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',

    # Kept short on purpose. Logout revokes the refresh token, but an access
    # token stays valid until it expires - nothing can recall one already
    # issued - so this window is how long a "logged out" token still works.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Each refresh issues a new refresh token and blacklists the one used, so
    # a stolen token stops working as soon as the real user refreshes.
    # Rotation without blacklisting would leave the old token valid.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# CORS - the Next.js frontend calls this API from a different origin.

CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
