"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read configuration from environment variables, falling back to the defaults
# below so a fresh clone runs without a .env file. No .env of any kind is
# committed - README.md lists the keys and what each one does.
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CORS_ALLOWED_ORIGINS=(list, ['http://localhost:3000', 'http://127.0.0.1:3000']),
)
environ.Env.read_env(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'SECRET_KEY',
    default='django-insecure-=ql$!y7ntt6q_i*eef@_9101061=*jk8+)6s3or_w@%*nlhenl',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Production hardening. Everything here is scoped to DEBUG=False so local
# development is unaffected - none of it works over plain http, and turning
# it on locally just makes the dev server unreachable.
if not DEBUG:
    # Render terminates TLS at its proxy and forwards over http, so Django
    # only learns the original request was https from this header. Without
    # it, SECURE_SSL_REDIRECT sees http and redirects forever.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Start at one hour. Raise it once the deployment is known good - HSTS is
    # hard to walk back, since browsers cache the instruction for its full
    # duration and will refuse http for that long.
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    # Stores issued refresh tokens so logout and rotation can revoke them.
    # Adds two tables; they are framework infrastructure, not part of the ERD.
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    # Uploads only. Image.url is a plain URLField, so Cloudinary is never
    # wired in as a Django storage backend - see CLOUDINARY_STORAGE below.
    'cloudinary',

    'accounts',
    'dashboard',
    'meal_plans',
    'recipes',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CorsMiddleware must sit above CommonMiddleware so CORS headers are
    # attached even to responses CommonMiddleware short-circuits.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Defaults to the local SQLite file so a fresh clone runs with no setup.
# Set DATABASE_URL to point at the real MySQL database once it is provisioned,
# e.g. mysql://user:password@127.0.0.1:3306/flavorshare
if env('DATABASE_URL', default=None):
    DATABASES = {'default': env.db('DATABASE_URL')}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded media (local dev; Cloudinary takes over in production)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Cloudinary
# https://cloudinary.com/documentation/django_integration
#
# Recipe photos are uploaded through POST /api/recipes/images/upload/, which
# hands the file to Cloudinary server-side and returns the hosted URL. Only
# that URL is stored, in Image.url - a plain URLField - so Cloudinary is never
# registered as a Django storage backend and STORAGES stays untouched. Keeping
# the API secret on this side is the point: the frontend never sees it.
#
# Blank by default so a fresh clone still starts. The upload endpoint checks
# for CLOUD_NAME and answers 503 with a readable message rather than failing
# somewhere inside the SDK. README.md lists the keys.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': env('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
}

# Largest file the upload endpoint will accept, in bytes. Checked before the
# file is sent anywhere, so an oversized upload costs nothing.
MAX_IMAGE_UPLOAD_BYTES = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Locked down by default: each view opts out with permission_classes.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    # Our User model's primary key is `user_id`, not Django's default `id`.
    # Without this SimpleJWT reads user.id when issuing a token and raises
    # AttributeError. USER_ID_CLAIM is already the default; stated here so
    # the pair stays visibly linked.
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',

    # Kept short on purpose. Logout revokes the refresh token, but an access
    # token stays valid until it expires - nothing can recall one already
    # issued - so this window is how long a "logged out" token still works.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Each refresh issues a new refresh token and blacklists the one used, so
    # a stolen token stops working as soon as the real user refreshes.
    # Rotation without blacklisting would leave the old token valid.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# CORS - the Next.js frontend calls this API from a different origin.

CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
