# Generated by Django 5.2.17 on 2026-09-12 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('posted', 'Posted a recipe'), ('edited', 'Edited a recipe'), ('commented', 'Left a review'), ('rated', 'Left a rating'), ('saved', 'Saved a recipe')], max_length=9)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'Activity',
                'ordering': ['-created_at', '-activity_id'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_created_idx')],
            },
        ),
    ]
