# Generated by Django 5.2.17 on 2026-09-18 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('recipes', '0003_recipe_external_id_recipe_source_recipe_source_url_and_more'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('inappropriate', 'Inappropriate content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=14)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=9)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.comment')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='recipes.recipe')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Report',
                'ordering': ['-created_at', '-report_id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipe__isnull', False), ('comment__isnull', True)), models.Q(('recipe__isnull', True), ('comment__isnull', False)), _connector='OR'), name='report_targets_exactly_one_thing')],
            },
        ),
    ]
