# Generated by Django 5.2.17 on 2026-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('posted', 'Posted a recipe'), ('edited', 'Edited a recipe'), ('commented', 'Left a review'), ('rated', 'Left a rating'), ('saved', 'Saved a recipe'), ('moderated', 'Took a moderation action')], max_length=9),
        ),
    ]
