# Generated by Django 5.2.17 on 2026-09-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MealPlan',
                'ordering': ['-start_date', '-meal_plan_id'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('meal_plan_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=9)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meal_plans.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='recipes.recipe')),
            ],
            options={
                'db_table': 'MealPlanEntry',
                'ordering': ['day', 'meal_plan_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('nutrition_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_info', to='recipes.recipe')),
            ],
            options={
                'db_table': 'NutritionInfo',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('start_date__isnull', True), ('end_date__isnull', True), _connector='OR'), name='meal_plan_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='mealplanentry',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'day', 'meal_type', 'recipe'), name='unique_recipe_per_meal_slot'),
        ),
    ]
