# Generated by Django 5.2.17 on 2026-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_external_id_recipe_source_recipe_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
